apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: my-demo-app
        image:
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: railsapp-secrets
                key: database-url


