# kube/service.yml

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: railsapp
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000